---
kind: pipeline
name: default

steps:
- name: frontend
  image: node:lts-alpine
  commands:
  - cd complex/frontend
  - npm install
  - npm test

---
kind: signature
hmac: abb98c5a2203e554a79036f5a82f5a8636a38e4456a478cb5dbc5fa8bbab40fe

...
