---
kind: pipeline
name: default

steps:
- name: frontend
  group: test
  image: node:lts-alpine
  commands:
  - cd complex/frontend
  - npm install
  - npm test
- name: qr-code
  group: test
  image: microsoft/dotnet:sdk
  commands:
  - cd complex/qr-code
  - dotnet test QrCodeTests
- name: question-list
  group: test
  image: golang:1.11
  commands:
  - cd complex/question-list
  - go test -mod=vendor
- name: question-submit
  group: test
  image: haskell:8
  commands:
  - true
  #- apt-get update
  #- apt-get install -y --no-install-recommends libpq-dev
  #- cd complex/question-submit
  #- cabal new-update
  #- cabal new-install
  #- cabal new-build

---
kind: signature
hmac: 1fd41c7bc2d8ffb8fb0840e893781a2854b3955b65957e40b5146ded7eac5325

...
