---
kind: pipeline
name: test

steps:

- name: frontend
  image: node:lts-alpine
  commands:
  - cd complex/frontend
  - npm install
  - npm test

- name: qr-code
  image: microsoft/dotnet:sdk
  commands:
  - cd complex/qr-code
  - dotnet test QrCodeTests

- name: question-list
  image: golang:1.11
  commands:
  - cd complex/question-list
  - go test -mod=vendor

- name: question-submit
  image: haskell:8
  commands:
  - true

---
kind: pipeline
name: deploy
depends_on: [test]

steps:
- name: frontend
  image: governmentpaas/cf-cli
  commands:
  - cd complex/
  - cf push tdln-frontend
- name: qr-code
  image: governmentpaas/cf-cli
  commands:
  - cd complex/
  - cf push tdln-qr-code
- name: question-list
  image: governmentpaas/cf-cli
  commands:
  - cd complex/
  - cf push tdln-question-list
- name: question-submit
  image: governmentpaas/cf-cli
  commands:
  - cd complex/
  - cf push tdln-question-list

---
kind: signature
hmac: 2e3f04d07bc6ca5cd181d2f253acb81604a3a45b13aabcce24ee5484942d8790

...
