---
kind: pipeline
name: test

steps:

- name: frontend
  image: node:lts-alpine
  commands:
  - true
  - # cd complex/frontend
  - # npm install
  - # npm test

- name: qr-code
  image: microsoft/dotnet:sdk
  commands:
  - true
  - # cd complex/qr-code
  - # dotnet test QrCodeTests

- name: question-list
  image: golang:1.11
  commands:
  - true
  - # cd complex/question-list
  - # go test -mod=vendor

- name: question-submit
  image: haskell:8
  commands:
  - true

---
kind: pipeline
name: deploy
depends_on: [test]

steps:
- name: frontend
  image: governmentpaas/cf-cli
  environment:
    CF_USERNAME:
      from_secret: PAAS_USERNAME
    CF_PASSWORD:
      from_secret: PAAS_PASSWORD
  commands:
  - cd complex/
  - cf api https://api.london.cloud.service.gov.uk
  - cf auth
  - cf target -o govuk-paas -s tdln
  - cf push tdln-frontend

- name: qr-code
  image: governmentpaas/cf-cli
  environment:
    CF_USERNAME:
      from_secret: PAAS_USERNAME
    CF_PASSWORD:
      from_secret: PAAS_PASSWORD
  commands:
  - cd complex/
  - cf api https://api.london.cloud.service.gov.uk
  - cf auth
  - cf target -o govuk-paas -s tdln
  - cf push tdln-qr-code

- name: question-list
  image: governmentpaas/cf-cli
  environment:
    CF_USERNAME:
      from_secret: PAAS_USERNAME
    CF_PASSWORD:
      from_secret: PAAS_PASSWORD
  commands:
  - cd complex/
  - cf api https://api.london.cloud.service.gov.uk
  - cf auth
  - cf target -o govuk-paas -s tdln
  - cf push tdln-question-list

- name: question-submit
  image: governmentpaas/cf-cli
  commands:
  environment:
    CF_USERNAME:
      from_secret: PAAS_USERNAME
    CF_PASSWORD:
      from_secret: PAAS_PASSWORD
  commands:
  - cd complex/
  - cf api https://api.london.cloud.service.gov.uk
  - cf auth
  - cf target -o govuk-paas -s tdln
  - cf push tdln-question-submit

---
kind: signature
hmac: 1fd7cb313e25483a13da8c11a094c94bed42fbc39882296e0270720a581dbb01

...
